### ISSUE TITLE
KeyError: 'active'

### ISSUE THREAD

**Issue by n8v-guy** [n8v-guy/slag#39]
View details in Rollbar: [https://rollbar.com/n8v/slag/items/13/](https://rollbar.com/n8v/slag/items/13/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 175, in stat
    '  <h1>' + self.archive.people_stat() + '</h1>'
  File "/app/slack_archive.py", line 543, in people_stat
    total = sum([person['active'] for person in self.people.values()])
KeyError: 'active'
```

**Comment by n8v-guy** [comment]
Resolved in f9d3e764b71b0c344ed45d6fa9ea8563d51e49e0
