### ISSUE TITLE
OperationFailure: database error: Unable to execute query: error processing query: ns=slag.messages limit=100 skip=0
Tree: $and
    to $in [ "C085Q1T4Y" "C08757N3C" "C087DTL7L" "C0886H533" "C08AG8YRJ" "C08FSM58F" "C08SMU6SG" "C09LGR40K" "C0BM90R1N" "C0BNG

### ISSUE THREAD

**Issue by n8v-guy** [n8v-guy/slag#44]
View details in Rollbar: [https://rollbar.com/n8v/slag/items/29/](https://rollbar.com/n8v/slag/items/29/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 256, in search
    results = self.archive.find_messages(query, stream_ids, page)
  File "/app/slack_archive.py", line 550, in find_messages
    return self._search_messages(condition, page)
  File "/app/slack_archive.py", line 569, in _search_messages
    return self._prepare_messages(query)
  File "/app/slack_archive.py", line 85, in _prepare_messages
    for res in query:
  File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 1097, in next
    if len(self.__data) or self._refresh():
  File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 1019, in _refresh
    self.__read_concern))
  File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 903, in __send_message
    codec_options=self.__codec_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/helpers.py", line 128, in _unpack_response
    error_object)
OperationFailure: database error: Unable to execute query: error processing query: ns=slag.messages limit=100 skip=0
Tree: $and
    to $in [ "C085Q1T4Y" "C08757N3C" "C087DTL7L" "C0886H533" "C08AG8YRJ" "C08FSM58F" "C08SMU6SG" "C09LGR40K" "C0BM90R1N" "C0BNG7N59" "C0DBMH095" "C0S58E2NR" "C0SCFSK7Z" "C0WHF1HB3" "C0XM5M6JX" "D161X11NZ" ]
    TEXT : query=EUR, language=, tag=NULL
Sort: { ts: -1 }
Proj: {}
 planner returned error: need exactly one text index for $text query
```

**Comment by n8v-guy** [comment]
Debugging issue, never pushed
