### ISSUE TITLE
KeyError: u'ilya.bogin'

### ISSUE THREAD

**Issue by n8v-guy** [n8v-guy/slag#46]
View details in Rollbar: [https://rollbar.com/n8v/slag/items/33/](https://rollbar.com/n8v/slag/items/33/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.66.0.49/newrelic/hooks/framework_flask.py", line 98, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.66.0.49/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "./app.py", line 293, in browse
    results, total = self.archive.stream_messages(stream, page)
  File "/app/slack_archive.py", line 561, in stream_messages
    return self._prepare_messages(query)
  File "/app/slack_archive.py", line 91, in _prepare_messages
    res['msg'] = markup.Markup(res['msg'], self.people, self.streams)
  File "/app/markup.py", line 107, in __init__
    msg = self.re_iter(LINK_RE, self.parse_link, msg)
  File "/app/markup.py", line 77, in re_iter
    part = re.sub(regexp, replace, prev)
  File "/app/.heroku/python/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/app/markup.py", line 59, in parse_link
    return self.link_user(target)
  File "/app/markup.py", line 50, in link_user
    return Markup.link_page('javascript:void(0)', self.user_name(user))
  File "/app/markup.py", line 38, in user_name
    return '@'+self.people[user[1:]]['login']
  File "/app/mongo_store.py", line 63, in __getitem__
    return self._store[key]
KeyError: u'ilya.bogin'
```

**Comment by n8v-guy** [comment]
Same stacktrace as in #45
