### ISSUE TITLE
KeyError: 'fileSize' (support MongoDB new version)

### ISSUE THREAD

**Issue by n8v-guy** [n8v-guy/slag#53]
View details in Rollbar: [https://rollbar.com/n8v/slag/items/48/](https://rollbar.com/n8v/slag/items/48/)

```
Traceback (most recent call last):
  File "/home/mshashkov/slag/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mshashkov/slag/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mshashkov/slag/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mshashkov/slag/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mshashkov/slag/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 176, in stat
    stat = self.archive.stat()
  File "/home/mshashkov/slag/slack_archive.py", line 621, in stat
    mongo_stat['fileSize'] / 1024 / 1024,
KeyError: 'fileSize'
```

**Comment by n8v-guy** [comment]
This section on stats page is going to be deleted
